### ISSUE TITLE
2-10版本出现意料之外的问题

### ISSUE THREAD

**Issue by sdsaz1531** [592767809/Class_And_Movies_Down_BYYG#10]
![QQ截图20210219110719](https://user-images.githubusercontent.com/79295366/108452406-65516180-72a3-11eb-85c9-c45c9a998696.png)
当我输入视频序号按下回车就报错

**Comment by sdsaz1531** [comment]
是有下载限制吗

**Comment by 592767809** [comment]
> 是有下载限制吗

可能是你cookie不正确

**Comment by sdsaz1531** [comment]
> > 是有下载限制吗
> 
> 可能是你cookie不正确

已经解决感谢感谢
